apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: microservices-demo-operator
  template:
    metadata:
      labels:
        name: microservices-demo-operator
    spec:
      serviceAccountName: microservices-demo-operator
      containers:
        - name: microservices-demo-operator
          image: quay.io/jmckind/microservices-demo-operator:latest
          command:
          - microservices-demo-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "microservices-demo-operator"
          resources: {}
